info:
  app:
    name: pro-zuul
    version: 1.0.0

management:
  security:
    enabled: false

zuul:
  routes:
    api-a:
      path: /api-user/**
      serviceId: pro-user
#    api-b:
#      path: /api-serv/**
#      serviceId: pro-user
    local:
      path: /local/**
      url: forward:/local


token:
  filter:
    skipUrl: login,regist,hi
    

